"""add data

Revision ID: c0d15fea3ded
Revises: a976f37724c0
Create Date: 2024-09-03 04:15:05.519475

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0d15fea3ded'
down_revision: Union[str, None] = 'a976f37724c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        INSERT INTO public.images (id, path, size, mime_type, filter, modified_at) VALUES
        ('870f0e6f-02ca-473d-bcc3-868719a7d612', 'uploads/example_3.jpg', 4880, 'image/jpeg', 'invert', '2024-09-03 01:05:35.633362'),
        ('c1a85c7f-4802-4465-b9cb-e145a4cb5b82', 'uploads/example_2.jpg', 10441, 'image/jpeg', 'canny', '2024-09-03 01:05:47.201946'),
        ('fc2e74c5-04c6-4bfd-8d8f-816e49f780a8', 'uploads/example_1.jpg', 511700, 'image/jpeg', 'canny', '2024-09-03 01:05:54.425555');
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM images WHERE id IN ('870f0e6f-02ca-473d-bcc3-868719a7d612', 'c1a85c7f-4802-4465-b9cb-e145a4cb5b82', 'fc2e74c5-04c6-4bfd-8d8f-816e49f780a8')")
    # ### end Alembic commands ###
